services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAT_MODEL=${CHAT_MODEL:-gpt-4o-mini}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
      - CHROMA_PATH=${CHROMA_PATH:-data/chroma}
      - CHROMA_COLLECTION=${CHROMA_COLLECTION:-docs}
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  rag-ui:
    build: .
    ports:
      - "8501:8501"
    environment:
      - RAG_API_URL=http://rag-api:8000
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./.env:/app/.env:ro
    command: ["streamlit", "run", "src/ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    depends_on:
      - rag-api

networks:
  default:
    name: rag-network